### ISSUE TITLE
ウィンドウサイズいっぱいに描画される問題

### ISSUE THREAD

**Issue by Raclamusi** [nokotan/OpenSiv3D#25]
**エラーの内容**

ウィンドウの形状にかかわらず、ウィンドウサイズいっぱいに描画されます。

![image](https://user-images.githubusercontent.com/61970673/183817316-29932029-7307-4d4d-85f5-ee4997ddb0c4.png)

```
Uncaught TypeError: Options.setFramebufferSize is not a function
    at doResize (OpenSiv3Dv0_6ForWebTest.html:21:1039)
    at callRuntimeCallbacks (OpenSiv3Dv0_6ForWebTest.js:9:46906)
    at postRun (OpenSiv3Dv0_6ForWebTest.js:9:35135)
    at doRun (OpenSiv3Dv0_6ForWebTest.js:9:391619)
    at OpenSiv3Dv0_6ForWebTest.js:9:391759
```

**再現方法**

[Visual Studio 用のセットアップガイド](https://siv3d.kamenokosoft.com/ja/building/overview)に従ってインストールして、何も変更せずビルド、実行しました。
Debug, Release にかかわらず発生します。

**発生環境**

 - OS: Windows 11 Home
 - GPU: Intel(R) UHD Graphics
 - ブラウザ: Chrome, Firefox, Edge など
 - Siv3D バージョン: 0.6.4

**Comment by Raclamusi** [comment]
下のコードを挿入しても同様の問題が発生します。
```c++
Scene::SetResizeMode(ResizeMode::Keep);
Scene::Resize(800, 600);
```

**Comment by nokotan** [comment]
ご報告ありがとうございます。

この現象は、v0.6.4r3 の既知のデグレです。

すでに、原因は解明されており、次期リリース v0.6.5 において解消予定です。

一時的に回避するには、`Template/Embeddable/web-player.js` に以下の通りセミコロンを挿入してください。

```diff
  Module["getCurrentAudioContext"] = function() {
    return Module["SDL2"].audioContext;
  };

  Module["getCurrentAudioSource"] = function() {
    return Module["SDL2"].audio.scriptProcessorNode;
- }
+ };

  // TODO: fix emscripten side
  Module["setFramebufferSize"] = function(width, height) {
    if (!GLFW.active) return;
    let resizeNeeded = true;

    if (GLFW.active.width != width || GLFW.active.height != height) {
      GLFW.active.width = width;
      GLFW.active.height = height;
    } else {
      resizeNeeded = false;
    }

    if (resizeNeeded) {
      const canvas = Module['canvas'];
      canvas.width = GLFW.active.width;
      canvas.height = GLFW.active.height;

      GLFW.onWindowSizeChanged();
      GLFW.onFramebufferSizeChanged();
    }
- }
+ };
```

**Comment by Raclamusi** [comment]
うまくいきました。
ありがとうございます。
